language: node_js
node_js:
  - 14
cache:
  directories:
    - node_modules
  script:
    - npm run build
    - npm run export
    - touch out/.nojekyll
  deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GHTOKEN
    local_dir: out
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(main)$
